export const REQUEST_COSTORDER_OFFLOWNO = 'REQUEST_COSTORDER_OFFLOWNO'
export const RECEIVE_COSTORDER_OFFLOWNO = 'RECEIVE_COSTORDER_OFFLOWNO'
export const INVALID_COSTORDER_OFFLOWNO = 'INVALID_COSTORDER_OFFLOWNO'

export const REQUEST_COSTITEM_LOAD = 'REQUEST_COSTITEM_LOAD'
export const RECEIVE_COSTITEM_LOAD = 'RECEIVE_COSTITEM_LOAD'

export const REQUEST_COSTORDER_OFPRCODE = 'REQUEST_COSTORDER_OFPRCODE'
export const RECEIVE_COSTORDER_OFPRCODE = 'RECEIVE_COSTORDER_OFPRCODE'
export const INVALID_COSTORDER_OFPRCODE = 'INVALID_COSTORDER_OFPRCODE'

export const REQUEST_COSTORDER_EDIT = 'REQUEST_COSTORDER_EDIT'
export const RECEIVE_COSTORDER_EDIT = 'RECEIVE_COSTORDER_EDIT'

export const FETCH_STATUS_SUCCESS = 'SUCCESS'
export const FETCH_STATUS_EXCEPTION = 'EXCEPTION'
export const FETCH_STATUS_FAILURE = 'FAILURE'